# Environment file for gymnasium-solver (uv/jupyter kernel)
[project]
name = "gymnasium-solver-env"
dependencies = [
    "python>=3.9",
    "gymnasium[box2d]",
    "torch",
    "numpy",
    "stable-baselines3",
    "wandb",
    "swig",
    "pytorch-lightning",
    "tsilva-notebook-utils==0.0.121",
    "ipykernel",
    "jupyter"
]

[tool.uv]
# Optional: specify uv settings here
