name: pong-objects-ppo-bayes
project: ALE-Pong-v5
method: bayes
metric:
  name: train/roll/ep_rew/mean
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 100

parameters:
  policy_lr:
    min: 0.0005
    max: 0.005
  clip_range:
    min: 0.15
    max: 0.3
  n_epochs:
    values: [8, 10, 15]
  ent_coef:
    min: 0.005
    max: 0.05
  batch_size:
    values: [256, 512, 1024]
  hidden_dims:
    values: [[64, 64], [128, 128], [64, 64, 64]]
  n_steps:
    values: [128, 256, 512]

program: train.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --config_id
  - "ALE-Pong-v5:objects_ppo"
  - --wandb_sweep
