# MountainCar with reward shaping challenge configurations

MountainCar-v0_rewardshaping_ppo:
  env_id: MountainCar-v0
  algo_id: ppo
  frame_stack: 3
  normalize: true
  env_wrappers:
    - id: RewardShaper_MountainCarV0
      position_reward_scale: 100.0
      velocity_reward_scale: 10.0
      height_reward_scale: 50.0
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  n_epochs: 10
  batch_size: 128
  n_steps: 128
  gae_lambda: 0.95
  gamma: 0.999
  ent_coef: 0.01
  clip_range: 0.2
  learning_rate: 3e-4
  hidden_dims: [256, 256]
  max_epochs: 1000

MountainCar-v0_rewardshaping_reinforce:
  env_id: MountainCar-v0
  algo_id: reinforce
  frame_stack: 3
  normalize_obs: true
  env_wrappers:
    - id: RewardShaper_MountainCarV0
      position_reward_scale: 100.0
      velocity_reward_scale: 10.0
      height_reward_scale: 50.0
  n_envs: 8
  n_epochs: 1
  ent_coef: 0.01
  n_steps: 1024
  batch_size: 128
  gamma: 0.999
  learning_rate: 1e-3
  hidden_dims: [128, 128]
  use_baseline: true
  max_epochs: 2000
