# Pong with RGB observations challenge configurations

Pong-v5_rgb_ppo:
  env_id: ALE/Pong-v5
  algo_id: ppo
  obs_type: "rgb"
  frame_stack: 4  # RGB observations typically benefit from frame stacking
  n_envs: 8
  policy: 'CnnPolicy'      # CNN policy for RGB observations
  n_steps: 128             # Smaller steps for CNN processing
  batch_size: 256
  n_epochs: 4
  gae_lambda: 0.95
  gamma: 0.99
  ent_coef: 0.01
  clip_range: 0.1
  learning_rate: 2.5e-4    # Lower learning rate for CNN
  eval_freq_epochs: 100    # Less frequent eval due to computational cost
  eval_episodes: 5
  vf_coef: 0.5
  max_grad_norm: 0.5

Pong-v5_rgb_reinforce:
  env_id: ALE/Pong-v5
  algo_id: reinforce
  obs_type: "rgb"
  frame_stack: 4
  n_envs: 4                # Fewer envs due to computational complexity
  policy: 'CnnPolicy'
  n_epochs: 1
  ent_coef: 0.01
  n_steps: 512
  batch_size: 64
  gamma: 0.99
  learning_rate: 1e-4      # Lower learning rate for CNN
  use_baseline: true
  max_epochs: 5000
