# Complementary environment info for FrozenLake-v1
source: https://gymnasium.farama.org/environments/toy_text/frozen_lake/
reward_structure:
  description: Sparse rewards; +1 for reaching goal, 0 otherwise.
reward_range: [0.0, 1.0]


