# Complementary env info for PettingZoo Go

rewards:
  # Go is outcome-based; per-step rewards are usually 0, final +/-1
  reward_unit: 1.0
  threshold: null
  threshold_solved: null

reward_range: [-1, 1]

action_space:
  # On 9x9, legal positions are 81 plus pass/resign; PZ masks illegal moves.
  discrete: 83
  labels: null

notes: |
  This describes the PettingZoo Go environment (parallel). The agent wrapper
  in this repo controls the first agent and auto-plays opponents randomly.
  Legal move masking should be handled by the env; the policy may still need
  to learn to avoid illegal moves if masking isn't enforced in the wrapper.


