# Complementary environment info for ViZDoom Deadly Corridor
source: https://vizdoom.cs.put.edu.pl/competitions/cig-2017/scenarios/#deadly-corridor
reward_structure:
  description: Deadly Corridor rewards approaching armor vest; penalizes retreat and death.
  components:
    - name: distance_shaping
      sign: positive
      note: Reward proportional to decrease in distance to vest each step.
    - name: retreat_penalty
      sign: negative
      note: Penalty proportional to increase in distance to vest.
    - name: death_penalty
      value: -100.0
      note: Large penalty on death.
reward_threshold: 1000.0
reward_range: [-100.0, 1000.0]
action_labels:
  0: noop
  1: forward
  2: backward
  3: strafe_left
  4: strafe_right
  5: turn_left
  6: turn_right
  7: attack
  8: forward_attack
