# Acrobot standard challenge configurations

__Acrobot-v1:
  project_id: "Acrobot-v1"
  env_id: Acrobot-v1
Acrobot-v1_ppo:
  inherits: __Acrobot-v1
  algo_id: ppo
  n_envs: 16
  n_timesteps: 1e6
  n_epochs: 4
  batch_size: 64
  normalize: true
  n_steps: 256
  gae_lambda: 0.94
  ent_coef: 0.0

Acrobot-v1_reinforce:
  inherits: __Acrobot-v1
  algo_id: reinforce
  n_envs: 8
  n_steps: 512
  batch_size: 64
  learning_rate: 5e-4
  hidden_dims: [128, 128]
  use_baseline: true
  max_epochs: 2000
