# Pong with object-based observations and deterministic environment challenge configurations

env_id: ALE/Pong-v5
obs_type: "objects"
env_wrappers:
  - id: PongV5_FeatureExtractor
env_kwargs:
  repeat_action_probability: 0.0  # Makes the environment deterministic
gamma: 0.99
hidden_dims: [128, 128]
eval_episodes: 10

reinforce:
  algo_id: reinforce
  n_envs: 16
  n_steps: 1024
  batch_size: 4096
  policy_lr: 1e-4
  normalize_returns: "baseline"
  ent_coef: 0.05
  eval_freq_epochs: 20 

# SOLVED: 3M timesteps (~17m)
ppo:
  algo_id: ppo
  max_timesteps: 3.3e6
  n_envs: 16
  n_steps: 256 
  batch_size: 1024
  n_epochs: 10
  ent_coef: 0.003
  clip_range: 0.15
  policy_lr: 3e-4
  eval_freq_epochs: 50