# Pong with object-based observations challenge configurations

env_id: ALE/Pong-v5
max_timesteps: 1e7
obs_type: "objects"
hidden_dims: [256, 256] 
eval_freq_epochs: 50 
eval_episodes: 10  
env_wrappers:
  - id: PongV5_FeatureExtractor

ppo:
  algo_id: ppo
  n_envs: 20
  subproc: true
  vf_coef: 0.5
  n_epochs: 20
  n_steps: 1024
  batch_size: 0.125
  ent_coef: 0.01
  clip_range: 0.2
  policy_lr: 1e-2 # approx_kl = inf if 1e-1
  normalize_advantages: "rollout"
