# ALE/Pong-v5
source: https://ale.farama.org/environments/pong/
description: Control right paddle; score when ball passes opponent, lose when it passes you.

render_fps: 60

action_space:
  discrete: 6
  labels: {0: NOOP, 1: FIRE, 2: RIGHT, 3: LEFT, 4: RIGHTFIRE, 5: LEFTFIRE}
  full_space: {count: 18, enable_with: full_action_space=True}

observation_space:
  default: state
  variants:
    state:
      shape: [8]
      dtype: float32
      components:
        - {name: Player.y, range: [-4.8, 4.8]}
        - {name: Player.dy, range: [-inf, inf]}
        - {name: Enemy.y, range: [-4.8, 4.8]}
        - {name: Enemy.dy, range: [-inf, inf]}
        - {name: Ball.x, range: [-4.8, 4.8]}
        - {name: Ball.y, range: [-4.8, 4.8]}
        - {name: Ball.dx, range: [-4.8, 4.8]}
        - {name: Ball.dy, range: [-4.8, 4.8]}

rewards:
  per_point: +1/-1
  episodic: score difference
  range: [-21, 21]
  threshold_solved: 19

modes:
  values: [0,1]
  default: 0

difficulties:
  values: [0,1,2,3]
  default: 0