# ALE/Pong-v5
source: https://ale.farama.org/environments/pong/
description: Control right paddle; score when ball passes opponent, lose when it passes you.

render_fps: 60

action_space:
  discrete: 6
  labels: {0: NOOP, 1: FIRE, 2: RIGHT, 3: LEFT, 4: RIGHTFIRE, 5: LEFTFIRE}
  full_space: {count: 18, enable_with: full_action_space=True}

observation_space:
  default: state
  variants:
    state:
      shape: [8]
      dtype: float32
      components:
        - {name: Player.y,  range: [0.0, 1.0]}
        - {name: Player.dy, range: [0.0, 1.0]}
        - {name: Enemy.y,   range: [0.0, 1.0]}
        - {name: Enemy.dy,  range: [0.0, 1.0]}
        - {name: Ball.x,    range: [0.0, 1.0]}
        - {name: Ball.y,    range: [0.0, 1.0]}
        - {name: Ball.dx,   range: [0.0, 1.0]}
        - {name: Ball.dy,   range: [0.0, 1.0]}

rewards:
  per_point: +1/-1
  range: [-1, 1]

returns:
  episodic: score difference (player score - opponent score)
  range: [-21, 21]
  threshold_solved: 19

modes:
  values: [0,1]
  default: 0

difficulties:
  values: [0,1,2,3]
  default: 0
