# Pong with object-based observations challenge configurations

env_id: ALE/Pong-v5
n_timesteps: 1e7
obs_type: "objects"
env_wrappers:
  - id: PongV5_FeatureExtractor

reinforce:
  algo_id: reinforce
  n_envs: 16
  n_steps: 1024
  batch_size: 4096
  learning_rate: 1e-3
  hidden_dims: [128, 128]
  eval_freq_epochs: 20 
  eval_episodes: 10  

ppo:
  algo_id: ppo
  n_envs: 32
  vf_coef: 0.7
  n_steps: 256
  batch_size: 2048 
  n_epochs: 6
  ent_coef: 0.006
  clip_range: lin_0.2 
  learning_rate: lin_3e-4 
  hidden_dims: [256, 256] 
  eval_freq_epochs: 50 
  eval_episodes: 10  
