# =====================
# Environment Specification
# =====================
spec: &spec
  source: local gym_envs.mab_env.MultiArmedBanditEnv
  description: Stateless multi-armed bandit; pull an arm to receive a stochastic reward.

  action_space:
    discrete: 10

  observation_space:
    default: constant_zero
    variants:
      constant_zero:
        shape: [n_arms]
        dtype: float32
        range: [0, 0]

  rewards:
    distribution: Gaussian per-arm; reward ~ N(means[i], stds[i])
    range: [-inf, inf]

  returns:
    episodic: reward per step (episode_length typically 1)
    range: [-inf, inf]


# =====================
# Configuration Anchors
# =====================

_env: &env
  env_id: Bandit-v0
  env_kwargs:
    n_arms: 10
    means: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    stds: 1
    episode_length: 1
  max_env_steps: 20_000
  gamma: 1.0
  gae_lambda: 1.0
  n_steps: 64
  eval_warmup_epochs: 5
  eval_freq_epochs: 1

# PPO on Multi-Armed Bandit - standard configuration for bandit problem
ppo:
  <<: *env
  algo_id: ppo
  description: "PPO on Multi-Armed Bandit - standard configuration for bandit problem"
  n_epochs: 4
  policy_lr: {start: 4e-2, end: 0.0}

# REINFORCE on Multi-Armed Bandit - smoke testing configuration
reinforce:
  <<: *env
  algo_id: reinforce
  description: "REINFORCE on Multi-Armed Bandit - smoke testing configuration"
  policy_lr: {start: 4e-2, end: 0.0}
