env_id: Bandit-v0
env_kwargs:
  n_arms: 10
  means: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  stds: 1
  episode_length: 1
max_timesteps: 2e5
#eval_freq_epochs: 10
eval_episodes: 100
eval_freq_epochs: null
early_stop_on_train_threshold: false
early_stop_on_eval_threshold: false

# PPO sample tuned for quick debugging
ppo:
  algo_id: ppo
  n_envs: 16
  n_steps: 64
  batch_size: 0.25     # fraction of rollout size
  n_epochs: 4
  policy_lr: 3e-3
  clip_range: 0.2
  gamma: 1.0           # single-step episodes
  gae_lambda: 1.0
  normalize_advantages: "rollout"
  
