env_id: Bandit-v0
seed: 42
eval_episodes: 50

# Environment parameters
env_kwargs:
  n_arms: 5
  means: [-0.5, 0.0, 0.2, 0.4, 1.0]
  stds: 0.1
  episode_length: 1

# PPO sample tuned for quick debugging
ppo:
  algo_id: ppo
  n_envs: 16
  n_steps: 64
  batch_size: 0.25     # fraction of rollout size
  n_epochs: 4
  policy_lr: 3e-3
  clip_range: 0.2
  gamma: 1.0           # single-step episodes
  gae_lambda: 1.0
  normalize_advantages: "rollout"
  max_timesteps: 20000
  eval_freq_epochs: 10
  early_stop_on_train_threshold: false
  early_stop_on_eval_threshold: false
  reward_threshold: 0.8 # TODO: make tsure this is propagated to env info

