
env_id: CartPole-v1
eval_episodes: 10
gamma: 0.98
ent_coef: 0.01

ppo:
  algo_id: ppo
  n_timesteps: 1e5
  n_envs: 8
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  n_epochs: 20
  learning_rate: lin_0.001
  clip_range: lin_0.2
  eval_freq_epochs: 100

# NOTE: 1638400
#reinforce:
#  algo_id: reinforce
#  n_timesteps: 2e6
#  n_envs: 8
#  n_steps: 1024
#  batch_size: 2048
#  learning_rate: 5e-4
#  eval_freq_epochs: 50

# NOTE: 1228800
#reinforce:
#  algo_id: reinforce
#  n_timesteps: 2e6
#  n_envs: 8
#  n_steps: 1024
#  batch_size: 2048
#  learning_rate: 5e-3
#  eval_freq_epochs: 25


# NOTE: 245760
#reinforce:
#  algo_id: reinforce
#  n_timesteps: 5e5
#  n_envs: 8
#  n_steps: 1024
#  batch_size: 2048
#  learning_rate: 5e-3
#  eval_freq_epochs: 10


reinforce:
  algo_id: reinforce
  #n_timesteps: 5e5
  n_envs: 16
  n_steps: 1024
  batch_size: 4096
  learning_rate: 3e-4
  normalize_returns: "baseline"
  normalize_advantages: true
  #eval_warmup_epochs: 60 # TODO: not converging... why?
  #eval_freq_epochs: 10 # TODO: ENSURE THIS RUNS AT EPOCH 20\