
env_id: CartPole-v1
eval_episodes: 10
gamma: 0.98
ent_coef: 0.01
eval_episodes: 100

# TODO: x metric cant be total timesteps because that increases with parallelization.... must be n_updates? index by epoch? or add updates metric?
# NOTE: 409600 245760
# TODO: anneal learning rate
# optimal single metric for best training
reinforce:
  algo_id: reinforce
  n_timesteps: 3e5
  n_envs: 8
  n_steps: 1024
  batch_size: 2048
  learning_rate: 6e-3
  eval_freq_epochs: 10

ppo:
  algo_id: ppo
  n_timesteps: 1e5
  n_envs: 8
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  n_epochs: 20
  learning_rate: lin_0.001
  clip_range: lin_0.2
  eval_freq_epochs: 100

