# CartPole standard challenge configurations

__CartPole-v1:
  project_id: "CartPole-v1"
  env_id: CartPole-v1
  frame_stack: 1
  policy: 'MlpPolicy'

__CartPole-v1_normalized:
  inherits: __CartPole-v1
  normalize_obs: "static"

CartPole-v1_ppo:
  inherits: __CartPole-v1
  algo_id: ppo
  n_envs: 8
  n_timesteps: !!float 1e5
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  gamma: 0.98
  ent_coef: 0.0
  n_epochs: 20
  learning_rate: 0.001
  #learning_rate: lin_0.001
  clip_range: 0.2
  #clip_range: lin_0.2
  hidden_dims: [64, 64]
  normalize_advantages: "rollout"

 # eval_freq_epochs: 10
 # eval_episodes: 5
 # eval_recording_freq_epochs: 1000000

CartPole-v1_reinforce:
  inherits: __CartPole-v1
  algo_id: reinforce
  n_envs: 8
  n_epochs: 1
  ent_coef: 0.01
  n_steps: 512
  batch_size: 64
  gamma: 0.99
  learning_rate: 5e-4
  hidden_dims: [64]
  use_baseline: false

# CartPole with normalized observations challenge configurations

CartPole-v1_normalized_ppo:
  inherits: __CartPole-v1_normalized
  algo_id: ppo
  n_envs: 8
  n_timesteps: !!float 1e6
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  gamma: 0.98
  ent_coef: 0.0
  n_epochs: 20
  learning_rate: 1e-3
  clip_range: 0.2
  hidden_dims: [64]

CartPole-v1_normalized_reinforce:
  inherits: __CartPole-v1_normalized
  algo_id: reinforce
  n_envs: 8
  n_epochs: 1
  ent_coef: 0.01
  n_steps: 512
  batch_size: 64
  gamma: 0.99
  learning_rate: 5e-4
  hidden_dims: [64]
  use_baseline: false
