# CartPole-v1 from RGB pixels using CNN policy

_base: &base
  env_id: CartPole-v1
  # Use environment wrapper to expose pixels as observations
  env_wrappers:
    - id: PixelObservationWrapper
      pixels_only: true
  # Image-specific preprocessing
  frame_stack: 4
  # Select CNN policy and configure a small CNN
  policy: cnn
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  eval_freq_epochs: 10
  eval_episodes: 5

ppo:
  <<: *base
  algo_id: ppo
  n_envs: 8
  max_timesteps: 5e5
  n_steps: 64
  batch_size: 512
  gae_lambda: 0.95
  gamma: 0.99
  ent_coef: 0.001
  n_epochs: 4
  policy_lr: lin_2.5e-4
  clip_range: lin_0.2
