env_id: CartPole-v1
eval_freq_epochs: 100        # evaluate every 5 training epochs
eval_episodes: 10           # run 10 episodes per evaluation
env_wrappers:
  - id: CartPoleV1_RewardShaper
    angle_reward_scale: 1.0
    position_reward_scale: 0.25
    clip_potential: true

ppo:
  algo_id: ppo
  n_envs: 8
  max_timesteps: 1e5
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  gamma: 0.98
  ent_coef: 0.0
  n_epochs: 20
  policy_lr: lin_0.001
  clip_range: lin_0.2
