
env_id: CartPole-v1
gamma: 1.0
ent_coef: 0.01
eval_episodes: 100

# NOTE: tuned, trains in 13 epochs (122880 steps)
# TODO: eval wramup
reinforce:
  algo_id: reinforce
  n_timesteps: 3e5
  n_envs: 8
  n_steps: 1024
  batch_size: 2048
  learning_rate: 6e-3
  eval_freq_epochs: 5
  frame_stack: 2 # Converges faster with frame stacking = 2, probably because it allows to estimate momentum better?

ppo:
  algo_id: ppo
  #n_timesteps: 200000        # you’ll usually “solve” long before this
  n_envs: 8
  n_steps: 128
  batch_size: 256
  n_epochs: 10               # gradient passes per update
  learning_rate: 5e-4        # higher than SB3 default; fine for CartPole
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  #ent_coef: 0.0              # CartPole doesn’t need extra entropy
  #vf_coef: 0.5
  #max_grad_norm: 0.5
  #target_kl: 0.03            # early stop per update if KL spikes
  normalize_advantages: true
  