
seed: 42 # TODO: try different seed
env_id: CartPole-v1
algo_id: reinforce
max_timesteps: 3e5
normalize_obs: False # Normalization doesn't seem to help
n_envs: 8
n_steps: 1024
policy_lr: 6e-3
hidden_dims: [64, 64] # TODO: try changing this
gamma: 0.99 # TODO: try increasing
ent_coef: 0.0 # TODO: try increasing
frame_stack: 1 # TODO: try changing this
# TODO: try deterministic eval
# TODO: monitor gradients
eval_freq_epochs: 5
eval_episodes: 100

# Unsolved: 300k timesteps
reinforce_vanilla:
  returns_type: "mc:episode"
  policy_targets: "returns"

# Solved: 82k timesteps
reinforce_rtg:
  returns_type: "mc:rtg"
  policy_targets: "returns"
  normalize_returns: "batch"

reinforce_baseline:
  returns_type: "mc:episode"
  advantages_type: "baseline"
  policy_targets: "advantages"
  normalize_advantages: "batch"

# TODO: same as using returns... investigate
# Solved: 82k timesteps
reinforce_baseline_rtg:
  returns_type: "mc:rtg"
  advantages_type: "baseline"
  policy_targets: "advantages"
  normalize_advantages: "batch"

ppo:
  #seed: 100 # TODO: seed setting does not seem to be doing anything
  algo_id: ppo
  n_envs: 8
  n_steps: 32
  batch_size: 256
  n_epochs: 20
  policy_lr: lin_0.001
  gae_lambda: 0.8
  clip_range: lin_0.2
  eval_freq_epochs: 100
  #frame_stack: 2 # TODO: not converging faster with frame stacking here, why?