# CartPole standard challenge configurations

CartPole-v1_ppo:
  env_id: CartPole-v1
  algo_id: ppo
  frame_stack: 1
  n_envs: 8
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  gamma: 0.98
  ent_coef: 0.0
  n_epochs: 20
  learning_rate: 1e-3
  clip_range: 0.2
  hidden_dims: [64]

CartPole-v1_reinforce:
  env_id: CartPole-v1
  algo_id: reinforce
  frame_stack: 1
  n_envs: 8
  n_epochs: 1
  ent_coef: 0.01
  n_steps: 512
  batch_size: 64
  gamma: 0.99
  learning_rate: 5e-4
  hidden_dims: [64]
  use_baseline: false

# CartPole with normalized observations challenge configurations

CartPole-v1_normalized_ppo:
  env_id: CartPole-v1
  algo_id: ppo
  frame_stack: 1
  normalize_obs: "static"
  n_envs: 8
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  gamma: 0.98
  ent_coef: 0.0
  n_epochs: 20
  learning_rate: 1e-3
  clip_range: 0.2
  hidden_dims: [64]

CartPole-v1_normalized_reinforce:
  env_id: CartPole-v1
  algo_id: reinforce
  frame_stack: 1
  normalize_obs: "static"
  n_envs: 8
  n_epochs: 1
  ent_coef: 0.01
  n_steps: 512
  batch_size: 64
  gamma: 0.99
  learning_rate: 5e-4
  hidden_dims: [64]
  use_baseline: false
