env_id: CartPole-v1
eval_episodes: 10
gamma: 0.98
ent_coef: 0.0

ppo:
  algo_id: ppo
  n_timesteps: 1e5
  n_envs: 8
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  n_epochs: 20
  learning_rate: lin_0.001
  clip_range: lin_0.2
  eval_freq_epochs: 100

reinforce:
  algo_id: reinforce
  n_timesteps: 2e5
  n_envs: 8
  n_steps: 512
  batch_size: 64
  learning_rate: 5e-4
  #normalize_returns: "baseline"  # TODO: this seems to be optimal, others yield much worse results... why?
  eval_freq_epochs: 10