__CartPole-v1:
  project_id: "CartPole-v1"
  env_id: CartPole-v1
  eval_episodes: 10
  eval_deterministic: false

CartPole-v1_ppo:
  inherits: __CartPole-v1
  algo_id: ppo
  n_envs: 8
  n_timesteps: 1e5
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  gamma: 0.98
  ent_coef: 0.0
  n_epochs: 20
  learning_rate: lin_0.001
  clip_range: lin_0.2
  eval_freq_epochs: 100

CartPole-v1_reinforce:
  inherits: __CartPole-v1
  algo_id: reinforce
  n_envs: 8
  n_steps: 512
  batch_size: 64
  learning_rate: 5e-4
  hidden_dims: [64]
  eval_freq_epochs: 5
