# FrozenLake-v1 deterministic challenge configurations

# =====================
# Environment Specification
# =====================
spec:
  source: https://gymnasium.farama.org/environments/toy_text/frozen_lake/
  description: Navigate a grid world from start to goal without falling into holes.

  action_space:
    discrete: 4
    labels: {0: LEFT, 1: DOWN, 2: RIGHT, 3: UP}

  observation_space:
    default: grid_4x4
    variants:
      grid_4x4: {n: 16, dtype: int64}
      grid_8x8: {n: 64, dtype: int64}

  rewards:
    on_goal: +1
    otherwise: 0
    range: [0, 1]

  returns:
    episodic: fraction of successes over episodes (stochastic)
    range: [0, 1]
    threshold_solved: 0.78

  versions:
    v1: Gymnasium FrozenLake deterministic variant

# =====================
# Configuration Anchors
# =====================

_env: &env
  env_id: FrozenLake-v1
  env_kwargs:
    is_slippery: true
    map_name: "4x4"
  env_wrappers:
    - id: DiscreteEncoder
      encoding: array
  eval_episodes: 10
  eval_freq_epochs: 10
  eval_recording_freq_epochs: 10

_env_deterministic: &env_deterministic
  <<: *env
  env_kwargs:
    is_slippery: false

_ppo: &ppo
  <<: *env
  algo_id: ppo
  n_envs: 8
  n_steps: 512
  batch_size: 0.25
  n_epochs: 10
  policy_lr: 9e-3
  hidden_dims: [64]

_reinforce: &reinforce
  <<: *env
  algo_id: reinforce
  max_timesteps: 2e5
  n_steps: 512
  batch_size: 64
  policy_lr: 0.005
  hidden_dims: [64]

ppo:
  <<: *ppo

ppo_deterministic:
  <<: [*env_deterministic, *ppo]

reinforce:
  <<: *reinforce

reinforce_deterministic:
  <<: [*env_deterministic, *reinforce]
