# FrozenLake-v1 deterministic challenge configurations
# TODO: reward shape to receive -1 on movement
# TODO: override reward threshold for deterministic

env_id: FrozenLake-v1
env_kwargs:
  is_slippery: false
  map_name: "4x4"
env_wrappers:
  - id: DiscreteEncoder
    encoding: array
eval_episodes: 10
eval_freq_epochs: 10
eval_recording_freq_epochs: 10

ppo:
  n_envs: 2
  algo_id: ppo
  max_timesteps: 1e5
  n_steps: 128                 # 16*128 = 2048 samples/update
  batch_size: 128              # 8 minibatches
  n_epochs: 10
  policy_lr: 0.0003
  hidden_dims: [64]            # Simple network for 16-state discrete environment

reinforce:
  algo_id: reinforce
  max_timesteps: 2e5
  n_steps: 512
  batch_size: 64
  policy_lr: 0.005
  hidden_dims: [64]
