# FrozenLake-v1 deterministic challenge configurations
# TODO: reward shape to receive -1 on movement
# TODO: override reward threshold for deterministic

_base: &base
  env_id: FrozenLake-v1
  env_kwargs:
    is_slippery: true
    map_name: "4x4"
  env_wrappers:
    - id: DiscreteEncoder
      encoding: array
  eval_episodes: 10
  eval_freq_epochs: 10
  eval_recording_freq_epochs: 10

# Optional environment variants (composable via YAML merges)
_env_deterministic: &env_deterministic
  <<: *base
  env_kwargs:
    is_slippery: false

# Algo presets
_ppo_base: &ppo_base
  <<: *base
  algo_id: ppo
  n_envs: 8
  n_steps: 512
  batch_size: 0.25
  n_epochs: 10
  policy_lr: 9e-3
  hidden_dims: [64]

_reinforce_base: &reinforce_base
  <<: *base
  algo_id: reinforce
  max_timesteps: 2e5
  n_steps: 512
  batch_size: 64
  policy_lr: 0.005
  hidden_dims: [64]

# Public variants
# SOLVED: 122k timesteps
ppo:
  <<: *ppo_base

ppo_deterministic:
  <<: [*env_deterministic, *ppo_base]

reinforce:
  <<: *reinforce_base

reinforce_deterministic:
  <<: [*env_deterministic, *reinforce_base]
