# FrozenLake-v1 deterministic challenge configurations

_env: &env
  env_id: FrozenLake-v1
  env_kwargs:
    is_slippery: true
    map_name: "4x4"
  env_wrappers:
    - id: DiscreteEncoder
      encoding: array
  eval_episodes: 10
  eval_freq_epochs: 10
  eval_recording_freq_epochs: 10

_env_deterministic: &env_deterministic
  <<: *env
  env_kwargs:
    is_slippery: false

_ppo: &ppo
  <<: *env
  algo_id: ppo
  n_envs: 8
  n_steps: 512
  batch_size: 0.25
  n_epochs: 10
  policy_lr: 9e-3
  hidden_dims: [64]

_reinforce: &reinforce
  <<: *env
  algo_id: reinforce
  max_timesteps: 2e5
  n_steps: 512
  batch_size: 64
  policy_lr: 0.005
  hidden_dims: [64]

ppo:
  <<: *ppo

ppo_deterministic:
  <<: [*env_deterministic, *ppo]

reinforce:
  <<: *reinforce

reinforce_deterministic:
  <<: [*env_deterministic, *reinforce]

