env_id: go
eval_episodes: 10
# PettingZoo Go takes board_size in env_kwargs
env_kwargs:
  board_size: 9

ppo_small9:
  algo_id: ppo
  n_envs: 8
  n_timesteps: 2e5
  n_steps: 64
  batch_size: 512
  gae_lambda: 0.95
  gamma: 0.99
  ent_coef: 0.01
  n_epochs: 4
  policy_lr: lin_0.0003
  clip_range: lin_0.2
  policy: mlp
  hidden_dims: [256, 256]
  eval_freq_epochs: 25
