env_id: LunarLander-v3
eval_episodes: 10
hidden_dims: [128, 128]
n_envs: 16
n_steps: 1024
ent_coef: 0.25
#max_timesteps: 1e6
#max_episode_steps: 500

reinforce_baseline:
  algo_id: reinforce
  returns_type: "mc:episode"
  advantages_type: "baseline"
  policy_targets: "advantages"
  #normalize_advantages: "batch"

reinforce_baseline2:
  algo_id: reinforce
  returns_type: "mc:rtg"          # was "mc:episode"
  advantages_type: "baseline"
  policy_targets: "advantages"
  normalize_advantages: "rollout" # or "batch"
  ent_coef: 0.01                  # was 0.25
  n_epochs: 2                     # reuse data once (optional)
  # Optionally shrink the batch per update:
  # n_steps: 512   # was 1024

# SOLVED: 983040 timesteps (~33m)
ppo:
  algo_id: ppo
  n_envs: 16
  max_timesteps: 1e6
  n_steps: 1024
  batch_size: 64
  gae_lambda: 0.98
  gamma: 0.999
  n_epochs: 4
  ent_coef: 0.01
  eval_freq_epochs: 10
  policy_targets: "advantages"
  normalize_advantages: "batch"