env_id: LunarLander-v3
eval_freq_epochs: 5
eval_episodes: 10

ppo:
  algo_id: ppo
  n_envs: 16
  n_timesteps: 1e6
  n_epochs: 4
  batch_size: 64
  n_steps: 1024
  gae_lambda: 0.98
  gamma: 0.999

reinforce:
  algo_id: reinforce
  n_envs: 8
  n_steps: 1024
  batch_size: 128
  gamma: 0.999
  learning_rate: 1e-3
  hidden_dims: [128, 128]
  use_baseline: true
  max_epochs: 2000
