# =====================
# Environment Specification
# =====================
spec:
  source: https://gymnasium.farama.org/environments/box2d/lunar_lander/
  description: Land a lunar module safely between flags on the surface.

  action_space:
    discrete: 4
    labels: {0: do_nothing, 1: fire_left, 2: fire_main, 3: fire_right}

  observation_space:
    default: state
    variants:
      state:
        shape: [8]
        dtype: float32
        components:
          - {name: x_position, range: [-inf, inf]}
          - {name: y_position, range: [-inf, inf]}
          - {name: x_velocity, range: [-inf, inf]}
          - {name: y_velocity, range: [-inf, inf]}
          - {name: angle, range: [-inf, inf]}
          - {name: angular_velocity, range: [-inf, inf]}
          - {name: left_leg_contact, values: [0, 1]}
          - {name: right_leg_contact, values: [0, 1]}

  rewards:
    shaping: dense; +100..140 for landing, -100 for crash; small per-step shaping
    threshold_solved: 200

# =====================
# Configuration Anchors
# =====================

_env: &env
  env_id: LunarLander-v3
  eval_episodes: 10
  hidden_dims: [128, 128]
  n_envs: 16
  n_steps: 1024
  ent_coef: 0.25

_reinforce: &reinforce
  <<: *env
  algo_id: reinforce

_ppo: &ppo
  <<: *env
  algo_id: ppo
  n_envs: 12
  max_env_steps: 5e6
  n_steps: 512
  batch_size: 256
  gae_lambda: 0.98
  gamma: 0.999
  n_epochs: 4
  policy_lr: 5e-4
  ent_coef: 0.01
  eval_warmup_epochs: 50
  eval_freq_epochs: 10
  policy_targets: "advantages"
  normalize_advantages: "batch"

reinforce_baseline:
  <<: *reinforce
  returns_type: "mc:episode"
  advantages_type: "baseline"
  policy_targets: "advantages"
  description: "REINFORCE with baseline - uses value function baseline for variance reduction"

reinforce_baseline2:
  <<: *reinforce
  returns_type: "mc:rtg"
  advantages_type: "baseline"
  policy_targets: "advantages"
  normalize_advantages: "rollout"
  ent_coef: 0.01
  n_epochs: 2
  description: "REINFORCE with baseline and return-to-go - combines both variance reduction techniques"

# PPO on LunarLander - standard configuration for lunar landing task
ppo:
  <<: *ppo
  description: "PPO on LunarLander - standard configuration for lunar landing task"
