_env: &env
  env_id: LunarLander-v3
  eval_episodes: 10
  hidden_dims: [128, 128]
  n_envs: 16
  n_steps: 1024
  ent_coef: 0.25

_reinforce: &reinforce
  <<: *env
  algo_id: reinforce

_ppo: &ppo
  <<: *env
  algo_id: ppo
  n_envs: 12
  max_timesteps: 5e6
  n_steps: 512
  batch_size: 256
  gae_lambda: 0.98
  gamma: 0.999
  n_epochs: 4
  policy_lr: 5e-4
  ent_coef: 0.01
  eval_warmup_epochs: 50
  eval_freq_epochs: 10
  policy_targets: "advantages"
  normalize_advantages: "batch"

reinforce_baseline:
  <<: *reinforce
  returns_type: "mc:episode"
  advantages_type: "baseline"
  policy_targets: "advantages"

reinforce_baseline2:
  <<: *reinforce
  returns_type: "mc:rtg"
  advantages_type: "baseline"
  policy_targets: "advantages"
  normalize_advantages: "rollout"
  ent_coef: 0.01
  n_epochs: 2

ppo:
  <<: *ppo

