env_id: LunarLander-v3
eval_episodes: 10
hidden_dims: [128, 128]
n_envs: 16
n_steps: 1024
ent_coef: 0.25
#max_timesteps: 1e6

reinforce_baseline:
  algo_id: reinforce
  returns_type: "mc:episode"
  advantages_type: "baseline"
  policy_targets: "advantages"
  #normalize_advantages: "batch"

ppo:
  algo_id: ppo
  n_epochs: 4
  gae_lambda: 0.98
  gamma: 0.999
  eval_freq_epochs: 10
