# MountainCar standard challenge configurations

env_id: MountainCar-v0
eval_freq_epochs: 10
eval_episodes: 10

ppo:
  algo_id: ppo
  n_envs: 16
  max_timesteps: 1e6
  n_epochs: 10
  batch_size: 128
  n_steps: 128
  gamma: 0.999
  policy_lr: 3e-4
  hidden_dims: [256, 256]
  max_epochs: 1000

reinforce:
  algo_id: reinforce
  max_timesteps: 2e6
  n_envs: 8
  n_steps: 1024
  batch_size: 128
  gamma: 0.999
  policy_lr: 1e-3
  hidden_dims: [128, 128]
  max_epochs: 2000
