# MountainCar standard challenge configurations

env_id: MountainCar-v0
eval_warmup_epochs: 50
eval_freq_epochs: 10
eval_episodes: 10
hidden_dims: [128, 128]
gamma: 0.999

ppo:
  algo_id: ppo
  n_envs: 16
  n_steps: 1024
  batch_size: 0.25
  n_epochs: 10
  policy_lr: 1e-4

reinforce:
  algo_id: reinforce
  n_envs: 8
  n_steps: 1024
  batch_size: 0.25
  policy_lr: 1e-3
