# Pong with RGB observations challenge configurations

__Pong-v5_rgb:
  project_id: "Pong-v5_rgb"
  env_id: ALE/Pong-v5
  frame_stack: 4  # RGB observations typically benefit from frame stacking
  policy: 'CnnPolicy'      # CNN policy for RGB observations

Pong-v5_rgb_ppo:
  inherits: __Pong-v5_rgb
  algo_id: ppo
  n_envs: 8
  n_steps: 128             # Smaller steps for CNN processing
  batch_size: 256
  n_epochs: 4
  clip_range: 0.1
  learning_rate: 2.5e-4    # Lower learning rate for CNN
  eval_freq_epochs: 100    # Less frequent eval due to computational cost
  eval_episodes: 5
Pong-v5_rgb_reinforce:
  inherits: __Pong-v5_rgb
  algo_id: reinforce
  n_envs: 4                # Fewer envs due to computational complexity
  n_steps: 512
  batch_size: 64
  learning_rate: 1e-4      # Lower learning rate for CNN
  use_baseline: true
  max_epochs: 5000
