# Pong with object-based observations and deterministic environment challenge configurations

project_id: "Pong-v5_deterministic_objects"
env_id: ALE/Pong-v5
obs_type: "objects"
env_wrappers:
  - id: PongV5_FeatureExtractor
env_kwargs:
  repeat_action_probability: 0.0  # Makes the environment deterministic

# SOLVED: 3M timesteps (~17m)
ppo:
  algo_id: ppo
  n_envs: 16
  n_steps: 256 
  batch_size: 1024
  n_epochs: 10
  ent_coef: 0.003
  clip_range: 0.15
  learning_rate: 3e-4
  hidden_dims: [128, 128]
  eval_freq_epochs: 50
  eval_episodes: 10

reinforce:
  algo_id: reinforce
  n_envs: 8
  n_steps: 1024
  batch_size: 128
  learning_rate: 1e-3
  hidden_dims: [128, 128]
  use_baseline: true
  max_epochs: 2000
