# Pong with RGB observations challenge configurations

__Pong-v5_rgb:
  project_id: "Pong-v5_rgb"
  env_id: ALE/Pong-v5
  obs_type: "rgb"
  grayscale_obs: true
  resize_obs: true
  frame_stack: 2  # RGB observations typically benefit from frame stacking
  policy: 'cnn'      # CNN policy for RGB observations

Pong-v5_rgb_ppo:
  inherits: __Pong-v5_rgb
  algo_id: ppo
  n_envs: 8
  n_steps: 256             # 8*256 = 2048 samples/update
  batch_size: 1024         # 2k rollout → 2 minibatches of 1024
  n_epochs: 3
  clip_range: 0.1
  learning_rate: 1e-4      # Slightly lower LR for stability on pixels
  frame_stack: 4           # Improve temporal information (typical Atari default)
  activation: relu         # Use ReLU for CNNs
  eval_freq_epochs: 100    # Less frequent eval due to computational cost
  eval_episodes: 5

Pong-v5_rgb_reinforce:
  inherits: __Pong-v5_rgb
  algo_id: reinforce
  n_envs: 4                # Fewer envs due to computational complexity
  n_steps: 512
  batch_size: 64
  learning_rate: 1e-4      # Lower learning rate for CNN
  use_baseline: true
  max_epochs: 5000
