# SuperMarioBros-Nes with RGB observations (preprocessed to grayscale+84x84+frame-stack)

# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/Farama-Foundation/stable-retro
  description: >
    Side-scrolling platformer. Guide Mario through levels to reach the flagpole
    while avoiding enemies and hazards. Observations are raw game frames; rewards
    typically reflect in-game score/progress.

  render_fps: 60
   
  # TODO: figure out other actions
  # TODO: why stuck keys
  # TODO: why env end early
  # TODO: why showing only 0-8
  action_space:
    multibinary: 10
    labels: {
      0: B,
      1: unknown1,
      2: unknown2,
      3: unknown3,
      4: unknown4,
      5: dpad_down,
      6: dpad_left,
      7: dpad_right,
      8: A,
      9: unknown5
    }
    valid: [0, 5, 6, 7, 8]


  #action_space:
    # When using stable-retro with use_restricted_actions=FILTERED, actions are a
    # filtered discrete set of gamepad combinations. Exact count can vary by game.
  #  note: filtered discrete action set (retro.Actions.FILTERED)

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [240, 256, 3]
        dtype: uint8
        range: [0, 255]
        note: NES native resolution; pipeline typically grayscales+resizes+stacks frames.

  rewards:
    description: >
      Environment returns score/progress deltas; death or timeouts end episodes.
    components:
      - {name: score_delta, sign: positive}
      - {name: progress, sign: positive}
      - {name: death_penalty, sign: negative}


# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: Retro/SuperMarioBros-Nes
  render_mode: 'rgb_array'
  env_kwargs:
    state: "Level1-1"
  # RGB preprocessing for CNN policy
  policy: cnn_actorcritic
  grayscale_obs: true
  resize_obs: [84, 84]
  frame_stack: 4
  # Retro library only allows one emulator instance per process
  vectorization_mode: async
  env_wrappers:
    # TODO: turn this into first level citizen
    # Frame skip BEFORE reward shaper so reward shaping sees accumulated rewards
    - id: FrameSkipWrapper
      skip: 4 # [2, 5]  # Stochastic frame skip: randomly skip 2-5 frames each step
    - id: RetroSuperMarioBros_RewardShaper
      reward_scale: 1.0
      death_penalty: -10.0
      level_complete_bonus: 10.0
      time_penalty_scale: 0.02
      x_position_scale: 0.2
      score_scale: 0.002
  #  - id: StickyActionsWrapper
 #     sticky_buttons: {0: 0.95, 7: 0.10}  # dpad_right pressed 75% of the time

# =====================
# configs
# =====================

ppo:
  <<: *env
  project_id: Retro-SuperMarioBros-Nes
  algo_id: ppo
  model_id: mlp_small
  description: "PPO on SuperMarioBros - standard configuration for Mario platformer game"
  #max_env_steps: 3e6
  n_envs: 16 # TODO: faster training with more envs?
  n_steps: 1024
  batch_size: 0.25
  policy_lr: 5e-4
  ent_coef: 0.03 # TODO: how is entropy behaving?
  #max_episode_steps: 10_000
  #eval_warmup_epochs: 10
  eval_freq_epochs: 1
  eval_episodes: 1 # TODO: increase this