# SuperMarioBros-Nes with RGB observations (preprocessed to grayscale+84x84+frame-stack)

_env: &env
  env_id: Retro/SuperMarioBros-Nes
  env_kwargs:
    state: "Level1-1"
  policy: 'cnn'
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  grayscale_obs: true
  resize_obs: true
  frame_stack: 4
  accelerator: 'gpu'
  devices: 'auto'
  eval_freq_epochs: 5
  eval_episodes: 3

_ppo: &ppo
  <<: *env
  algo_id: ppo
  max_timesteps: 3e6
  n_envs: 8
  n_steps: 256
  batch_size: 1024
  n_epochs: 3
  clip_range: 0.1
  policy_lr: 1e-4
  eval_freq_epochs: 20
  eval_episodes: 5

ppo:
  <<: *ppo

