# SuperMarioBros-Nes with RGB observations (preprocessed to grayscale+84x84+frame-stack)

env_id: Retro/SuperMarioBros-Nes
policy: 'cnn'
policy_kwargs:
  activation: relu
  channels: [32, 64, 64]
  kernel_sizes: [8, 4, 3]
  strides: [4, 2, 1]
grayscale_obs: true
resize_obs: true
frame_stack: 4
env_kwargs:
  state: "Level1-1"       # Default starting level/state in stable-retro
accelerator: 'gpu'
devices: 'auto'
eval_freq_epochs: 5
eval_episodes: 3

ppo:
  algo_id: ppo
  n_envs: 8
  n_steps: 256
  batch_size: 1024
  n_epochs: 3
  clip_range: 0.1
  learning_rate: 1e-4
  frame_stack: 4
  eval_freq_epochs: 20
  eval_episodes: 5
