# Taxi standard challenge configurations

__Taxi-v3:
  project_id: "Taxi-v3"
  env_id: Taxi-v3
  policy: 'MlpPolicy'
  ent_coef: 0.5
  gae_lambda: 0.95
  gamma: 0.99
  n_envs: 16
  #n_timesteps: !!float 3e5
  frame_stack: 1
  eval_episodes: 10
  eval_deterministic: true
  eval_freq_epochs: 10
  eval_recording_freq_epochs: 10

Taxi-v3_ppo:
  inherits: __Taxi-v3
  algo_id: ppo
  n_steps: 64                  # 16*64 = 1024 samples/update
  batch_size: 256              # 4 minibatches

  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.1
  vf_coef: 0.5
  max_grad_norm: 0.5
  
  # Learning rate / entropy
  learning_rate: 0.0003
  ent_coef: 0.01               # consider decay → 0 over training

  # Network (adjust to encoding)
  # For 4-D ordinal or 9-bit binary: smaller net is enough
  hidden_dims: [128]        # or [64, 64] if using 19-d one-hot / embedding

  # Eval
  eval_episodes: 10
  eval_deterministic: true


Taxi-v3_reinforce:
  inherits: __Taxi-v3
  algo_id: reinforce
  n_epochs: 1
  n_steps: 256
  batch_size: 32
  gamma: 0.99
  learning_rate: 0.01
  hidden_dims: [128]
  use_baseline: true
