# Taxi standard challenge configurations

_env: &env
  env_id: Taxi-v3
  ent_coef: 0.01
  n_envs: 16
  eval_freq_epochs: 10
  eval_episodes: 10
  env_wrappers:
    - id: DiscreteEncoder
      encoding: array

_ppo: &ppo
  <<: *env
  algo_id: ppo
  max_timesteps: 10e6
  n_steps: 1024
  batch_size: 4096
  n_epochs: 20
  clip_range: 0.2
  policy_lr: 1e-2
  hidden_dims: [4, 16]
  normalize_returns: "rollout"
  normalize_advantages: "batch"
  vf_coef: 0.25

_reinforce: &reinforce
  <<: *env
  algo_id: reinforce
  max_timesteps: 5e5
  n_steps: 256
  batch_size: 32
  policy_lr: 0.01
  hidden_dims: [128]

ppo:
  <<: *ppo

reinforce:
  <<: *reinforce

