# Taxi standard challenge configurations

env_id: Taxi-v3
ent_coef: 0.5
n_envs: 16
eval_freq_epochs: 10
eval_episodes: 10

ppo:
  algo_id: ppo
  n_timesteps: 3e5
  n_steps: 64                  # 16*64 = 1024 samples/update
  batch_size: 256              # 4 minibatches

  n_epochs: 10
  clip_range: 0.1
  policy_lr: 0.0003
  hidden_dims: [128]        # or [64, 64] if using 19-d one-hot / embedding

  # Eval
  eval_episodes: 10

reinforce:
  algo_id: reinforce
  n_timesteps: 5e5
  n_steps: 256
  batch_size: 32
  policy_lr: 0.01
  hidden_dims: [128]
