# Taxi standard challenge configurations

__Taxi-v3:
  env_id: Taxi-v3
  policy: 'MlpPolicy'

Taxi-v3_ppo:
  inherits: __Taxi-v3
  algo_id: ppo
  n_envs: 8
  n_timesteps: !!float 5e5
  n_steps: 128
  batch_size: 64
  n_epochs: 4
  gae_lambda: 0.95
  gamma: 0.99
  ent_coef: 0.5
  learning_rate: 0.0003
  clip_range: 0.1
  hidden_dims: [256, 256]

Taxi-v3_reinforce:
  inherits: __Taxi-v3
  algo_id: reinforce
  frame_stack: 1
  n_envs: 8
  n_epochs: 1
  ent_coef: 0.01
  n_steps: 256
  batch_size: 32
  gamma: 0.99
  learning_rate: 0.001
  hidden_dims: [256, 256]
  use_baseline: true
  max_epochs: 1000
  reward_threshold: 8.0
