# VizDoom-DefendTheCenter-v0
source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#defend-the-center
description: Stand in the center and defend against approaching enemies from all sides.

render_fps: 35

action_space:
  discrete: 9
  labels: {0: noop, 1: forward, 2: backward, 3: strafe_left, 4: strafe_right, 5: turn_left, 6: turn_right, 7: attack, 8: forward_attack}

observation_space:
  default: rgb
  variants:
    rgb:
      shape: [height, width, 3]
      dtype: uint8
      range: [0, 255]
      note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

rewards:
  description: Survive and eliminate enemies; penalties for death.
  components:
    - {name: kill_reward, sign: positive}
    - {name: survival_time, sign: positive}
    - {name: death_penalty, value: -100.0}
  threshold_solved: 1000
  range: [-100, 2000]

versions:
  v0: Initial wrapper; RGB24 observations; exposes render_mode and frame_skip


reward_threshold: 1000
