# =====================
# Environment Specification
# =====================
spec:
  source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#health-gathering
  description: Survive in a toxic environment by gathering health vials to avoid death.
  goal: survive in a toxic environment by gathering health vials to avoid death.

  render_fps: 35

  action_space:
    discrete: 9
    labels: {
      0: noop, 
      1: forward, 
      2: backward, 
      3: strafe_left, 
      4: strafe_right, 
      5: turn_left, 
      6: turn_right, 
      7: attack, 
      8: forward_attack
    }

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Positive for survival time and picking health; negative on death.
    components:
      - {name: health_pickup, sign: positive}
      - {name: survival_time, sign: positive}
      - {name: death_penalty, value: -100.0}
    range: [-100, 2000]

  returns:
    threshold_solved: 1000


# =====================
# Configuration Anchors
# =====================

_env: &env
  env_id: VizDoom-HealthGathering-v0
  policy: 'cnn'
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  grayscale_obs: true
  resize_obs: true
  frame_stack: 4
  accelerator: 'gpu'
  devices: 'auto'
  eval_freq_epochs: 1
  eval_episodes: 1
  max_timesteps: 2e6
  n_envs: 8
  n_steps: 128
  batch_size: 256
  n_epochs: 4

_ppo: &ppo
  <<: *env
  algo_id: ppo
  clip_range: 0.1
  policy_lr: 2.5e-4

# PPO on VizDoom HealthGathering - standard configuration for health gathering survival task
ppo:
  <<: *ppo
  description: "PPO on VizDoom HealthGathering - standard configuration for health gathering survival task"
