# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#health-gathering
  description: Survive in a toxic environment by gathering health vials to avoid death.
  goal: survive in a toxic environment by gathering health vials to avoid death.

  render_fps: 35

  action_space:
    discrete: 9
    labels: {
      0: noop, 
      1: forward, 
      2: backward, 
      3: strafe_left, 
      4: strafe_right, 
      5: turn_left, 
      6: turn_right, 
      7: attack, 
      8: forward_attack
    }

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Positive for survival time and picking health; negative on death.
    components:
      - {name: health_pickup, sign: positive}
      - {name: survival_time, sign: positive}
      - {name: death_penalty, value: -100.0}
    range: [-100, 2000]

  returns:
    threshold_solved: 1000


# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: VizDoom-HealthGathering-v0
  render_mode: 'rgb_array'
    # TODO: defaults are not being applied
  obs_type: rgb
  render_mode: 'rgb_array'
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  grayscale_obs: true
  resize_obs: [84, 84]
  frame_stack: 4

# =====================
# configs
# =====================

ppo:
  <<: *env
  project_id: VizDoom-HealthGathering-v0
  algo_id: ppo
  description: "PPO on VizDoom HealthGathering - standard configuration for health gathering survival task"
  n_envs: 32
  n_steps: 256
  batch_size: 0.25
  policy_lr: 2.5e-4
  n_epochs: 15
  ent_coef: 0.03
  clip_range: 0.1
  eval_warmup_epochs: 10
  eval_freq_epochs: 10
  eval_episodes: 10
  target_kl: 0.01
