# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/Farama-Foundation/ViZDoom/blob/master/scenarios/take_cover.cfg
  description: Teach agent to link incoming missiles with estimated lifespan. Agent must dodge fireballs to survive.

  render_fps: 35

  action_space:
    discrete: 8
    labels: {
      0: noop, # mask
      1: forward, # mask
      2: backward, # mask
      3: strafe_left,
      4: strafe_right,
      5: turn_left, # mask
      6: turn_right, # mask
      7: attack # mask
    }

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Positive reward for survival time. Agent earns reward for each tic alive.
    components:
      - {name: survival_reward, value: 1.0, sign: positive}
    threshold_solved: 750
    range: [0, 2100]

# TODO: this is used to standardize vizdoom action spaces across environments
_env_wrapper_discrete_action_space_remapper: &env_wrapper_discrete_action_space_remapper
  id: DiscreteActionSpaceRemapperWrapper
  mapping: [0, 7, 2, 3, 4, 5, 6, 1]

# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: VizDoom-TakeCover-v0
  obs_type: rgb
  render_mode: 'rgb_array'
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  grayscale_obs: true
  resize_obs: [84, 84]
  frame_stack: 4
  env_wrappers:
    - *env_wrapper_discrete_action_space_remapper

# =====================
# configs
# =====================

ppo:
  <<: *env
  project_id: VizDoom-TakeCover-v0
  algo_id: ppo
  description: "PPO on VizDoom TakeCover - agent learns to dodge incoming missiles and survive"
  n_envs: 32
  n_steps: 256
  batch_size: 0.5
  policy_lr: 1e-3
  n_epochs: 20
  eval_warmup_epochs: 20
  eval_freq_epochs: 10
  eval_episodes: 10
