# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#defend-the-line
  description: Defend a line by eliminating enemies approaching from a single direction.

  render_fps: 35

  action_space:
    discrete: 9
    labels: {0: noop, 1: forward, 2: backward, 3: strafe_left, 4: strafe_right, 5: turn_left, 6: turn_right, 7: attack, 8: forward_attack}

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Reward for kills and survival time; penalties on death.
    components:
      - {name: kill_reward, sign: positive}
      - {name: survival_time, sign: positive}
      - {name: death_penalty, value: -100.0}
    threshold_solved: 1000
    range: [-100, 2000]


# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: VizDoom-DefendTheLine-v0
  render_mode: 'rgb_array'

# =====================
# configs
# =====================

ppo:
  <<: *env
  algo_id: ppo
  description: "PPO on VizDoom DefendTheLine - standard configuration for line defense task"
  eval_freq_epochs: 1
  eval_episodes: 1
  max_env_steps: 3e6
  n_steps: 128
  n_epochs: 4
  clip_range: 0.1
  policy_lr: 2.5e-4
