# VizDoom-DeadlyCorridor-v0
source: https://vizdoom.cs.put.edu.pl/competitions/cig-2017/scenarios/#deadly-corridor
description: Reach the armor vest through a corridor of enemies; survive and progress forward.

render_fps: 35

action_space:
  discrete: 9
  labels: {0: noop, 1: forward, 2: backward, 3: strafe_left, 4: strafe_right, 5: turn_left, 6: turn_right, 7: attack, 8: forward_attack}

observation_space:
  default: rgb
  variants:
    rgb:
      shape: [height, width, 3]
      dtype: uint8
      range: [0, 255]
      note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

rewards:
  description: Dense shaping towards the vest; penalties for retreat and death.
  components:
    - {name: distance_shaping, sign: positive}
    - {name: retreat_penalty, sign: negative}
    - {name: death_penalty, value: -100.0}
  threshold_solved: 1000
  range: [-100, 1000]

versions:
  v0: Initial wrapper; RGB24 observations; exposes render_mode and frame_skip

