# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/mwydmuch/ViZDoom/blob/master/scenarios/basic.cfg
  description: Simple scenario. Agent must pick up a can of health.

  render_fps: 35

  action_space:
    multibinary: 8
    labels: {
      0: noop,
      1: move_forward,
      2: move_backward,
      3: move_left,
      4: move_right,
      5: turn_left,
      6: turn_right,
      7: attack
    }
    valid: [3, 4, 7]  # Only move_left, move_right, and attack are available in this scenario

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Sparse reward for obtaining the object; small step penalties possible.
    components:
      - {name: pickup_reward, sign: positive}
      - {name: step_penalty, sign: negative}
    threshold_solved: 10
    range: [-10, 100]

# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: VizDoom-Basic-v0
  # TODO: defaults are not being applied
  obs_type: rgb
  render_mode: 'rgb_array'
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  grayscale_obs: true
  resize_obs: [84, 84]
  frame_stack: 4

# =====================
# configs
# =====================

ppo:
  <<: *env
  project_id: VizDoom-Basic-v0
  algo_id: ppo
  description: "PPO on VizDoom Basic - standard configuration for basic health gathering task"
  n_envs: 32
  n_steps: 256
  batch_size: 0.5
  policy_lr: 1e-3
  n_epochs: 20
  #eval_warmup_epochs: 20
  eval_freq_epochs: 1
  eval_episodes: 1

# TODO: test
#n_epochs: 10
#n_steps: 128
#batch_size: 0.25
#ent_coef: 0.01