# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/Farama-Foundation/ViZDoom/blob/master/scenarios/predict_position.cfg
  description: Teach agent to synchronize missile weapon shots with target movements. Agent must predict where moving monster will be.

  render_fps: 35

  action_space:
    discrete: 8
    labels: {
      0: noop,
      1: forward,
      2: backward,
      3: strafe_left,
      4: strafe_right,
      5: turn_left,
      6: turn_right,
      7: attack
    }
    valid: [5, 6, 7]

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Positive reward for killing monster, small negative living penalty to encourage efficiency.
    components:
      - {name: kill_reward, value: 1.0, sign: positive}
      - {name: living_penalty, value: -0.0001, sign: negative}
    threshold_solved: 0.5
    range: [-0.03, 1.0]

# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: VizDoom-PredictPosition-v0
  obs_type: rgb
  render_mode: 'rgb_array'
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  grayscale_obs: true
  resize_obs: [84, 84]
  frame_stack: 4

# =====================
# configs
# =====================

ppo:
  <<: *env
  project_id: VizDoom-PredictPosition-v0
  algo_id: ppo
  description: "PPO on VizDoom PredictPosition - agent learns to predict target position and time missile shots"
  n_envs: 32
  n_steps: 256
  batch_size: 0.5
  policy_lr: 1e-3
  n_epochs: 20
  eval_warmup_epochs: 20
  eval_freq_epochs: 10
  eval_episodes: 10
