# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#defend-the-center
  description: Stand in the center and defend against approaching enemies from all sides.

  render_fps: 35

  action_space:
    discrete: 9
    labels: {0: noop, 1: forward, 2: backward, 3: strafe_left, 4: strafe_right, 5: turn_left, 6: turn_right, 7: attack, 8: forward_attack}

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Survive and eliminate enemies; penalties for death.
    components:
      - {name: kill_reward, sign: positive}
      - {name: survival_time, sign: positive}
      - {name: death_penalty, value: -100.0}
    threshold_solved: 1000
    range: [-100, 2000]

# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: VizDoom-DefendTheCenter-v0
  render_mode: 'rgb_array'
  policy: 'cnn_actorcritic'
  env_wrappers:
    - { id: VizDoom_RewardShaper, noop_penalty: 0.01, move_reward: 0.004, turn_reward: 0.004 }

# =====================
# configs
# =====================

ppo:
  <<: *env
  algo_id: ppo
  description: "PPO on VizDoom DefendTheCenter - standard configuration for center defense task"
  eval_freq_epochs: 10
  eval_episodes: 1
  max_env_steps: 5e6
  n_steps: 256
  n_epochs: 4
  ent_coef: 0.01
  clip_range: {start: 0.2, end: 0.0}
  policy_lr: {start: 0.0003, end: 0.0}
