# =====================
# Environment Specification
# =====================
spec:
  source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#defend-the-center
  description: Stand in the center and defend against approaching enemies from all sides.

  render_fps: 35

  action_space:
    discrete: 9
    labels: {0: noop, 1: forward, 2: backward, 3: strafe_left, 4: strafe_right, 5: turn_left, 6: turn_right, 7: attack, 8: forward_attack}

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Survive and eliminate enemies; penalties for death.
    components:
      - {name: kill_reward, sign: positive}
      - {name: survival_time, sign: positive}
      - {name: death_penalty, value: -100.0}
    threshold_solved: 1000
    range: [-100, 2000]

# =====================
# Configuration Anchors
# =====================

_env: &env
  env_id: VizDoom-DefendTheCenter-v0
  policy: 'cnn'
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  grayscale_obs: true
  resize_obs: true
  frame_stack: 4
  accelerator: 'gpu'
  devices: 'auto'
  env_kwargs:
    frame_skip: 4
  env_wrappers:
    - { id: VizDoom_RewardShaper, noop_penalty: 0.01, move_reward: 0.004, turn_reward: 0.004 }
  eval_freq_epochs: 10
  eval_episodes: 1
  max_env_steps: 5e6
  n_envs: 16
  n_steps: 256
  batch_size: 512
  n_epochs: 4

_ppo: &ppo
  <<: *env
  algo_id: ppo
  ent_coef: 0.01
  clip_range: lin_0.2
  policy_lr: lin_0.0003
  gamma: 0.99
  gae_lambda: 0.95

ppo:
  <<: *ppo
  description: "PPO on VizDoom DefendTheCenter - standard configuration for center defense task"
