# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#health-gathering
  description: Survive in a toxic environment by gathering health vials to avoid death.
  goal: survive in a toxic environment by gathering health vials to avoid death.

  render_fps: 35

  action_space:
    discrete: 9
    labels: {
      0: noop, 
      1: forward, 
      2: backward, 
      3: strafe_left, 
      4: strafe_right, 
      5: turn_left, 
      6: turn_right, 
      7: attack, 
      8: forward_attack
    }

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Positive for survival time and picking health; negative on death.
    components:
      - {name: health_pickup, sign: positive}
      - {name: survival_time, sign: positive}
      - {name: death_penalty, value: -100.0}
    range: [-100, 2000]

  returns:
    threshold_solved: 1000


# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: VizDoom-HealthGathering-v0
  render_mode: 'rgb_array'

# =====================
# configs
# =====================

ppo:
  <<: *env
  project_id: VizDoom-HealthGathering-v0
  algo_id: ppo
  description: "PPO on VizDoom HealthGathering - standard configuration for health gathering survival task"
  eval_freq_epochs: 1
  eval_episodes: 1
  max_env_steps: 2e6
  n_steps: 128
  n_epochs: 4
  clip_range: 0.1
  policy_lr: 2.5e-4
