# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#defend-the-center
  description: Stand in the center and defend against approaching enemies from all sides.

  render_fps: 35

  action_space:
    discrete: 9
    labels: {0: noop, 1: forward, 2: backward, 3: strafe_left, 4: strafe_right, 5: turn_left, 6: turn_right, 7: attack, 8: forward_attack}

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Survive and eliminate enemies; penalties for death.
    components:
      - {name: kill_reward, sign: positive}
      - {name: survival_time, sign: positive}
      - {name: death_penalty, value: -100.0}
    threshold_solved: 1000
    range: [-100, 2000]

# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: VizDoom-DefendTheCenter-v0
  render_mode: 'rgb_array'
  policy: 'cnn_actorcritic'
  env_wrappers:
    - { id: VizDoom_RewardShaper, noop_penalty: 0.01, move_reward: 0.004, turn_reward: 0.004 }
    # TODO: defaults are not being applied
  obs_type: rgb
  render_mode: 'rgb_array'
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  grayscale_obs: true
  resize_obs: [84, 84]
  frame_stack: 4


# =====================
# configs
# =====================

# TODO: try no frame stack (should train faster and still work)

ppo:
  <<: *env
  project_id: VizDoom-DefendTheCenter-v0

  algo_id: ppo
  description: "PPO on VizDoom DefendTheCenter - standard configuration for center defense task"
  max_env_steps: 2e6
  n_envs: 32
  n_steps: 256
  batch_size: 0.25 # 0.5
  n_epochs: 20

  policy_lr:
    start: 2.5e-4
    end: 2.5e-5

  ent_coef: 0.03
  #  start: 0.03
  #  end: 0.01
  
  eval_warmup_epochs: 10
  eval_freq_epochs: 10
  eval_episodes: 10
