# =====================
# Environment Specification
# =====================
spec:
  source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#defend-the-line
  description: Defend a line by eliminating enemies approaching from a single direction.

  render_fps: 35

  action_space:
    discrete: 9
    labels: {0: noop, 1: forward, 2: backward, 3: strafe_left, 4: strafe_right, 5: turn_left, 6: turn_right, 7: attack, 8: forward_attack}

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Reward for kills and survival time; penalties on death.
    components:
      - {name: kill_reward, sign: positive}
      - {name: survival_time, sign: positive}
      - {name: death_penalty, value: -100.0}
    threshold_solved: 1000
    range: [-100, 2000]

  versions:
    v0: ViZDoom defend_the_line.cfg scenario

# =====================
# Configuration Anchors
# =====================

_env: &env
  env_id: VizDoom-DefendTheLine-v0
  policy: 'cnn'
  policy_kwargs:
    channels: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
  grayscale_obs: true
  resize_obs: true
  frame_stack: 4
  accelerator: 'gpu'
  devices: 'auto'
  eval_freq_epochs: 1
  eval_episodes: 1

_ppo: &ppo
  <<: *env
  algo_id: ppo
  max_timesteps: 3e6
  n_envs: 8
  n_steps: 128
  batch_size: 256
  n_epochs: 4
  clip_range: 0.1
  policy_lr: 2.5e-4

ppo:
  <<: *ppo
  description: "PPO on VizDoom DefendTheLine - standard configuration for line defense task"
