# =====================
# Environment Specification
# =====================
spec: &spec
  source: https://github.com/mwydmuch/ViZDoom/tree/master/scenarios#my-way-home
  description: Navigate a labyrinth to find the green vest. Agent spawns in random room facing random direction.

  render_fps: 35

  action_space:
    multibinary: 8
    labels: {
      0: noop,
      1: move_forward,
      2: move_backward,
      3: move_left,
      4: move_right,
      5: turn_left,
      6: turn_right,
      7: attack
    }
    valid: [1, 5, 6]  # Only move_forward, turn_left, and turn_right are available in this scenario

  observation_space:
    default: rgb
    variants:
      rgb:
        shape: [height, width, 3]
        dtype: uint8
        range: [0, 255]
        note: Height/width depend on the ViZDoom cfg; wrapper enforces RGB24 and HWC.

  rewards:
    description: Find the green vest as quickly as possible.
    components:
      - {name: vest_reward, sign: positive, value: 1.0}
      - {name: timestep_penalty, value: -0.0001, note: "Encourages faster navigation"}
    threshold_solved: 0.5
    range: [-0.21, 1.0]
    note: Episode terminates on vest collection or timeout (2100 frames / 60 seconds)

# =====================
# env variants
# =====================

# Base env
_env: &env
  spec: *spec
  env_id: VizDoom-MyWayHome-v0
  render_mode: 'rgb_array'
  policy: 'cnn_actorcritic'
  obs_type: rgb
  render_mode: 'rgb_array'
  grayscale_obs: true
  resize_obs: [84, 84]
  frame_stack: 4
  env_wrappers:
    - { id: VizDoom_RewardShaper, noop_penalty: 0.01, move_reward: 0.004, turn_reward: 0.004 }


# =====================
# configs
# =====================

ppo:
  <<: *env
  project_id: VizDoom-MyWayHome-v0

  algo_id: ppo
  model_id: cnn_nature
  description: "PPO on VizDoom MyWayHome - agent learns navigation in labyrinth to find vest"
  max_env_steps: 5e6
  n_envs: 32
  n_steps: 256
  batch_size: 0.25
  n_epochs: 20

  policy_lr:
    start: 2.5e-4
    end: 2.5e-5

  ent_coef: 0.03

  eval_warmup_epochs: 10
  eval_freq_epochs: 10
  eval_episodes: 10
