_wandb:
    value:
        cli_version: 0.21.0
        e:
            mkszaz8xfz19f03gfqu2u4sawz59oyk3:
                codePath: notebook.ipynb
                codePathLocal: notebook.ipynb
                email: eng.tiago.silva@gmail.com
                executable: /Users/tsilva/repos/tsilva/gymnasium-solver/.venv/bin/python
                git:
                    commit: f8887e4e627a7c743eb3ddf49c27886242afc392
                    remote: git@github.com:tsilva/gymnasium-solver.git
                host: Tiagos-MacBook-Pro.local
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/tsilva/repos/tsilva/gymnasium-solver/notebook.ipynb
                python: CPython 3.12.2
                root: .
                startedAt: "2025-07-16T14:57:48.243179Z"
                writerId: mkszaz8xfz19f03gfqu2u4sawz59oyk3
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
            "2":
                - 1
                - 9
                - 41
                - 103
            "3":
                - 2
                - 7
                - 13
                - 66
            "4": 3.12.2
            "5": 0.21.0
            "8":
                - 1
            "12": 0.21.0
            "13": darwin-arm64
