# CartPole-v1 Environment Configuration
# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/tree/master/hyperparams

default:
  eval_reward_threshold: -100
  train_rollout_interval: 1
  train_rollout_steps: 6000
  train_batch_size: 500
  eval_rollout_interval: 10
  eval_rollout_episodes: 10
  hidden_dims: [64, 64]
  gamma: 1.0
  entropy_coef: 0.0 

reinforce:
  policy_lr: 1e-3

ppo:
  policy_lr: 3e-3
  value_lr: 3e-3
  clip_epsilon: 0.2
  gae_lambda: 0.95