# CartPole-v1 Environment Configuration
# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/tree/master/hyperparams

default:
  reward_threshold: 475
  rollout_interval: 1
  train_rollout_steps: 2048
  batch_size: 2048
  eval_interval: 10
  eval_episodes: 10
  hidden_dims: [64, 64]

reinforce:
  policy_lr: 5e-3

ppo:
  policy_lr: 0.001
  value_lr: 0.001