# LunarLander-v3 Environment Configuration

default:
  reward_threshold: 200
  total_timesteps: 1000000  # TODO: call this n_timesteps
  gamma: 0.999
  lam: 0.98  # gae_lambda: 0.98  # TODO: this is not being propagated to collect_rollouts
  clip_epsilon: 0.2
  batch_size: 64
  eval_interval: 2
  policy_lr: 0.0001
  value_lr: 0.0005
  hidden_dim: 32
  entropy_coef: 0.01

reinforce:
  entropy_coef: 0.03
  batch_size: 128

ppo:
  # TODO: n_envs: 16, n_epochs: 4, n_steps: 1024
  # Uses default config with above TODO items
