# Complementary environment info for Pong-v4
source: https://ale.farama.org/environments/pong/
description: Control right paddle; score when ball passes opponent, lose when it passes you.

# Variant-specific settings
obs_type: rgb
frameskip: [2, 5]
repeat_action_probability: 0.00

