CartPole-v1:
  env_id: CartPole-v1
  n_envs: 8
  n_epochs: 1
  ent_coef: 0.01
  normalize_obs: false
  normalize_reward: false
  n_steps: 512
  batch_size: 64
  gamma: 0.99
  learning_rate: 5e-4
  hidden_dims: [64]
  frame_stack: 3

MountainCar-v0:
  env_id: MountainCar-v0
  n_envs: 8
  n_epochs: 1
  ent_coef: 0.01
  normalize_obs: false
  normalize_reward: false
  n_steps: 1024
  batch_size: 128
  gamma: 0.999
  learning_rate: 1e-3
  hidden_dims: [128, 128]
  frame_stack: 1
  max_epochs: 2000

MountainCar-v0_rewardshaping:
  inherit_from: MountainCar-v0
  normalize_obs: true
  env_wrappers:
    - id: RewardShaper_MountainCarV0
      position_reward_scale: 100.0
      velocity_reward_scale: 10.0
      height_reward_scale: 50.0
